title: OnDataEngineering Content Development Site
description: Jekyll site for the development of content for the OnDataEngineering site.
baseurl: ""
url: "http://localhost:4000"

markdown: kramdown
theme: minima

plugins:
  - jekyll-redirect-from

exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - README.md
    - CONTRIBUTING.md

permalink: /blog/:year/:month/:day/:title/

show_errors: true

excerpt_separator: "<!--more-->"

header_pages:
  - indexes/technologies.md
  - indexes/tech-categories.md
  - indexes/tech-vendors.md
  - posts.html
  
collections:
  technologies:
    output: true
    permalink: /technologies/:path/
  tech-categories:
    output: true
    permalink: /tech-categories/:path/
  tech-vendors:
    output: true
    permalink: /tech-vendors/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Peter
  -
    scope:
      path: ""
      type: "technologies"
    values:
      layout: technology
  -
    scope:
      path: ""
      type: "tech-categories"
    values:
      layout: tech_category
  -
    scope:
      path: ""
      type: "tech-vendors"
    values:
      layout: tech_vendor
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
  -
    scope:
      path: "indexes"
      type: "pages"
    values:
      layout: content
  -
    scope:
      path: "tech-categories"
      type: "pages"
    values:
      layout: content